# Generated by Django 2.2.5 on 2020-01-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200131_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_varified',
            new_name='email_verified',
        ),
    ]
